default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 25 } %>
  timeout: 5000
  host: <%= ENV["DATABASE_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  database: <%= ENV.fetch("POSTGRES_DB", "") %>

development:
  <<: *default

test:
  <<: *default
  database: app_test

stage:
  <<: *default

production:
  <<: *default
