# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

JudgeType.find_or_create_by(name: "Presentation", event_class: "Freestyle") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Mistakes: Dismounts",
    val_2_description: "Choreography & Style",
    val_3_description: "Showmanship and Originality",
    val_4_description: "Interpretation",
    val_1_max: 10,
    val_2_max: 15,
    val_3_max: 15,
    val_4_max: 10
  )
end
JudgeType.find_or_create_by(name: "Technical", event_class: "Freestyle") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Quantity of Unicycling Skills & Transitions",
    val_2_description: "Mastery and Quality of Execution",
    val_3_description: "Difficulty and Duration",
    val_4_description: "N/A",
    val_1_max: 10,
    val_2_max: 15,
    val_3_max: 15,
    val_4_max: 0
  )
end

JudgeType.find_or_create_by(name: "Flatland Judge Type", event_class: "Flatland") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Variety",
    val_2_description: "Consistency/Flow",
    val_3_description: "Difficulty",
    val_4_description: "Last Trick",
    val_1_max: 30,
    val_2_max: 30,
    val_3_max: 30,
    val_4_max: 9
  )
end

JudgeType.find_or_create_by(name: "High/Long Judge Type", event_class: "High/Long") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "?",
    val_2_description: "?",
    val_3_description: "?",
    val_4_description: "?",
    val_1_max: 10,
    val_2_max: 10,
    val_3_max: 10,
    val_4_max: 10
  )
end

JudgeType.find_or_create_by(name: "Street Judge Zone 1", event_class: "Street") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Score",
    val_2_description: "n/a",
    val_3_description: "n/a",
    val_4_description: "n/a",
    val_1_max: 100,
    val_2_max: 0,
    val_3_max: 0,
    val_4_max: 0
  )
end

JudgeType.find_or_create_by(name: "Street Judge Zone 2", event_class: "Street") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Score",
    val_2_description: "n/a",
    val_3_description: "n/a",
    val_4_description: "n/a",
    val_1_max: 100,
    val_2_max: 0,
    val_3_max: 0,
    val_4_max: 0
  )
end

JudgeType.find_or_create_by(name: "Street Judge Zone 3", event_class: "Street") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Score",
    val_2_description: "n/a",
    val_3_description: "n/a",
    val_4_description: "n/a",
    val_1_max: 100,
    val_2_max: 0,
    val_3_max: 0,
    val_4_max: 0
  )
end

JudgeType.find_or_create_by(name: "Performance", event_class: "Artistic Freestyle IUF 2015") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Mistakes: Dismounts",
    val_2_description: "Presence/Execution",
    val_3_description: "Composition/Choreography",
    val_4_description: "Interpretation of the Music/Timing",
    val_1_max: 10,
    val_2_max: 10,
    val_3_max: 10,
    val_4_max: 10
  )
end

JudgeType.find_or_create_by(name: "Technical", event_class: "Artistic Freestyle IUF 2015") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "Quantity of Unicycling Skills & Transitions",
    val_2_description: "Mastery and Quality of Execution",
    val_3_description: "Difficulty and Duration",
    val_4_description: "N/A",
    val_1_max: 10,
    val_2_max: 15,
    val_3_max: 15,
    val_4_max: 0
  )
end

JudgeType.find_or_create_by(name: "Writing", event_class: "Standard Skill") do |judge_type|
  judge_type.assign_attributes(
    val_1_description: "n/a",
    val_2_description: "n/a",
    val_3_description: "n/a",
    val_4_description: "n/a",
    val_1_max: 0,
    val_2_max: 0,
    val_3_max: 0,
    val_4_max: 0
  )
end

if WheelSize.count == 0
  WheelSize.create(position: 1, description: "16\" Wheel")
  WheelSize.create(position: 2, description: "20\" Wheel")
  WheelSize.create(position: 3, description: "24\" Wheel")
end

if StandardSkillEntry.count == 0
  StandardSkillEntry.create(description: "riding", number: 1, letter: 'a', points: 1.0)
  StandardSkillEntry.create(description: "riding - c", number: 1, letter: 'b', points: 1.3)
  StandardSkillEntry.create(description: "riding - 8", number: 1, letter: 'c', points: 1.5)
  StandardSkillEntry.create(description: "riding holding seatpost, one hand", number: 2, letter: 'a', points: 1.3)
  StandardSkillEntry.create(description: "riding holding seatpost, one hand - c", number: 2, letter: 'b', points: 1.6)
  StandardSkillEntry.create(description: "riding holding seatpost, one hand - 8", number: 2, letter: 'c', points: 1.9)
  StandardSkillEntry.create(description: "riding holding seatpost, two hands", number: 2, letter: 'd', points: 1.4)
  StandardSkillEntry.create(description: "riding holding seatpost, two hands - c", number: 2, letter: 'e', points: 1.8)
  StandardSkillEntry.create(description: "riding holding seatpost, two hands - 8", number: 2, letter: 'f', points: 2.0)
  StandardSkillEntry.create(description: "riding bwd", number: 3, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "riding bwd - c", number: 3, letter: 'b', points: 3.1)
  StandardSkillEntry.create(description: "riding bwd - 8", number: 3, letter: 'c', points: 3.6)
  StandardSkillEntry.create(description: "seat in front, seat against body", number: 4, letter: 'a', points: 2.0)
  StandardSkillEntry.create(description: "seat in front", number: 4, letter: 'b', points: 2.3)
  StandardSkillEntry.create(description: "seat in front - c", number: 4, letter: 'c', points: 2.9)
  StandardSkillEntry.create(description: "seat in front - 8", number: 4, letter: 'd', points: 3.3)
  StandardSkillEntry.create(description: "seat in front frh, seat against body", number: 4, letter: 'e', points: 3.3)
  StandardSkillEntry.create(description: "seat in front frh", number: 4, letter: 'f', points: 3.7)
  StandardSkillEntry.create(description: "seat in front frh - c", number: 4, letter: 'g', points: 4.3)
  StandardSkillEntry.create(description: "seat in front frh - 8", number: 4, letter: 'h', points: 4.8)
  StandardSkillEntry.create(description: "seat in front bwd, seat against body", number: 5, letter: 'a', points: 3.4)
  StandardSkillEntry.create(description: "seat in front bwd", number: 5, letter: 'b', points: 3.6)
  StandardSkillEntry.create(description: "seat in front bwd - c", number: 5, letter: 'c', points: 4.1)
  StandardSkillEntry.create(description: "seat in front bwd - 8", number: 5, letter: 'd', points: 4.7)
  StandardSkillEntry.create(description: "seat in front bwd frh, seat against body", number: 5, letter: 'e', points: 4.0)
  StandardSkillEntry.create(description: "seat in front bwd frh", number: 5, letter: 'f', points: 4.5)
  StandardSkillEntry.create(description: "seat in front bwd frh - c", number: 5, letter: 'g', points: 5.2)
  StandardSkillEntry.create(description: "seat in back, seat against body", number: 6, letter: 'a', points: 2.2)
  StandardSkillEntry.create(description: "seat in back", number: 6, letter: 'b', points: 2.5)
  StandardSkillEntry.create(description: "seat in back - c", number: 6, letter: 'c', points: 3.1)
  StandardSkillEntry.create(description: "seat in back - 8", number: 6, letter: 'd', points: 3.6)
  StandardSkillEntry.create(description: "seat in back bwd, seat against body", number: 7, letter: 'a', points: 3.5)
  StandardSkillEntry.create(description: "seat in back bwd", number: 7, letter: 'b', points: 3.9)
  StandardSkillEntry.create(description: "seat in back bwd - c", number: 7, letter: 'c', points: 4.5)
  StandardSkillEntry.create(description: "seat in back bwd - 8", number: 7, letter: 'd', points: 5.1)
  StandardSkillEntry.create(description: "seat on side, seat against body", number: 8, letter: 'a', points: 3.4)
  StandardSkillEntry.create(description: "seat on side, seat against body - c", number: 8, letter: 'b', points: 3.2)
  StandardSkillEntry.create(description: "seat on side", number: 8, letter: 'c', points: 4.1)
  StandardSkillEntry.create(description: "seat on side - c", number: 8, letter: 'd', points: 3.9)
  StandardSkillEntry.create(description: "seat on side bwd, seat against body", number: 9, letter: 'a', points: 4.3)
  StandardSkillEntry.create(description: "seat on side bwd", number: 9, letter: 'b', points: 4.6)
  StandardSkillEntry.create(description: "seat on side bwd - c", number: 9, letter: 'c', points: 4.4)
  StandardSkillEntry.create(description: "stomach on seat, 1 hand on seat", number: 10, letter: 'a', points: 2.1)
  StandardSkillEntry.create(description: "stomach on seat", number: 10, letter: 'b', points: 2.3)
  StandardSkillEntry.create(description: "stomach on seat - c", number: 10, letter: 'c', points: 2.9)
  StandardSkillEntry.create(description: "stomach on seat - 8", number: 10, letter: 'd', points: 3.3)
  StandardSkillEntry.create(description: "stomach on seat bwd", number: 11, letter: 'a', points: 3.8)
  StandardSkillEntry.create(description: "stomach on seat bwd - c", number: 11, letter: 'b', points: 4.4)
  StandardSkillEntry.create(description: "stomach on seat bwd - 8", number: 11, letter: 'c', points: 4.9)
  StandardSkillEntry.create(description: "chin on seat, 1 hand on seat", number: 12, letter: 'a', points: 3.5)
  StandardSkillEntry.create(description: "chin on seat", number: 12, letter: 'b', points: 4.0)
  StandardSkillEntry.create(description: "chin on seat - c", number: 12, letter: 'c', points: 4.6)
  StandardSkillEntry.create(description: "chin on seat - 8", number: 12, letter: 'd', points: 5.2)
  StandardSkillEntry.create(description: "chin on seat bwd, 1 hand on seat", number: 13, letter: 'a', points: 4.2)
  StandardSkillEntry.create(description: "chin on seat bwd", number: 13, letter: 'b', points: 4.9)
  StandardSkillEntry.create(description: "chin on seat bwd - c", number: 13, letter: 'c', points: 5.6)
  StandardSkillEntry.create(description: "chin on seat bwd - 8", number: 13, letter: 'd', points: 6.4)
  StandardSkillEntry.create(description: "drag seat in front", number: 14, letter: 'a', points: 4.1)
  StandardSkillEntry.create(description: "drag seat in front - c", number: 14, letter: 'b', points: 4.7)
  StandardSkillEntry.create(description: "drag seat in front - 8", number: 14, letter: 'c', points: 5.3)
  StandardSkillEntry.create(description: "drag seat in front bwd", number: 15, letter: 'a', points: 5.3)
  StandardSkillEntry.create(description: "drag seat in front bwd - c", number: 15, letter: 'b', points: 6.1)
  StandardSkillEntry.create(description: "drag seat in front bwd - 8", number: 15, letter: 'c', points: 6.9)
  StandardSkillEntry.create(description: "drag seat in back", number: 16, letter: 'a', points: 4.3)
  StandardSkillEntry.create(description: "drag seat in back - c", number: 16, letter: 'b', points: 4.9)
  StandardSkillEntry.create(description: "drag seat in back - 8", number: 16, letter: 'c', points: 5.6)
  StandardSkillEntry.create(description: "drag seat in back bwd", number: 17, letter: 'a', points: 6.0)
  StandardSkillEntry.create(description: "drag seat in back bwd - c", number: 17, letter: 'b', points: 6.9)
  StandardSkillEntry.create(description: "drag seat in back bwd - 8", number: 17, letter: 'c', points: 7.8)
  StandardSkillEntry.create(description: "riding sideways, seat against body", number: 18, letter: 'a', points: 5.6)
  StandardSkillEntry.create(description: "riding sideways", number: 18, letter: 'b', points: 5.7)
  StandardSkillEntry.create(description: "riding sideways 1 ft ext, seat against body", number: 18, letter: 'c', points: 6.0)
  StandardSkillEntry.create(description: "riding sideways seat drag", number: 18, letter: 'd', points: 6.3)
  StandardSkillEntry.create(description: "one foot", number: 19, letter: 'a', points: 3.0)
  StandardSkillEntry.create(description: "one foot - c", number: 19, letter: 'b', points: 3.5)
  StandardSkillEntry.create(description: "one foot - 8", number: 19, letter: 'c', points: 3.9)
  StandardSkillEntry.create(description: "one foot ext", number: 19, letter: 'd', points: 3.2)
  StandardSkillEntry.create(description: "one foot ext - c", number: 19, letter: 'e', points: 3.7)
  StandardSkillEntry.create(description: "one foot ext - 8", number: 19, letter: 'f', points: 4.2)
  StandardSkillEntry.create(description: "one foot crossed", number: 19, letter: 'g', points: 3.4)
  StandardSkillEntry.create(description: "one foot crossed - c", number: 19, letter: 'h', points: 3.9)
  StandardSkillEntry.create(description: "one foot crossed - 8", number: 19, letter: 'i', points: 4.4)
  StandardSkillEntry.create(description: "one foot bwd", number: 20, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "one foot bwd - c", number: 20, letter: 'b', points: 4.6)
  StandardSkillEntry.create(description: "one foot bwd - 8", number: 20, letter: 'c', points: 5.2)
  StandardSkillEntry.create(description: "one foot ext bwd", number: 20, letter: 'd', points: 4.4)
  StandardSkillEntry.create(description: "one foot ext bwd - c", number: 20, letter: 'e', points: 5.1)
  StandardSkillEntry.create(description: "one foot ext bwd - 8", number: 20, letter: 'f', points: 5.7)
  StandardSkillEntry.create(description: "one foot seat in front against body", number: 21, letter: 'a', points: 3.8)
  StandardSkillEntry.create(description: "one foot seat in front", number: 21, letter: 'b', points: 4.5)
  StandardSkillEntry.create(description: "one foot seat in front - c", number: 21, letter: 'c', points: 5.2)
  StandardSkillEntry.create(description: "one foot seat in front - 8", number: 21, letter: 'd', points: 5.9)
  StandardSkillEntry.create(description: "one foot ext, seat in front against body", number: 21, letter: 'e', points: 4.1)
  StandardSkillEntry.create(description: "one foot ext, seat in front against body - c", number: 21, letter: 'f', points: 4.7)
  StandardSkillEntry.create(description: "one foot seat in front against body bwd", number: 22, letter: 'a', points: 4.7)
  StandardSkillEntry.create(description: "one foot seat in front bwd", number: 22, letter: 'b', points: 5.4)
  StandardSkillEntry.create(description: "one foot seat in front bwd - c", number: 22, letter: 'c', points: 6.2)
  StandardSkillEntry.create(description: "one foot ext, seat in front against body bwd", number: 22, letter: 'd', points: 5.9)
  StandardSkillEntry.create(description: "one foot ext, seat in front against body bwd - c", number: 22, letter: 'e', points: 6.8)
  StandardSkillEntry.create(description: "seat on side, one foot, seat against body", number: 23, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "seat on side, one foot", number: 23, letter: 'b', points: 5.0)
  StandardSkillEntry.create(description: "seat on side, one foot - c", number: 23, letter: 'c', points: 4.8)
  StandardSkillEntry.create(description: "seat on side, one foot - 8", number: 23, letter: 'd', points: 6.5)
  StandardSkillEntry.create(description: "seat on side, one foot bwd, seat against body", number: 24, letter: 'a', points: 5.0)
  StandardSkillEntry.create(description: "seat on side, one foot bwd", number: 24, letter: 'b', points: 5.4)
  StandardSkillEntry.create(description: "seat on side, one foot bwd - c", number: 24, letter: 'c', points: 5.1)
  StandardSkillEntry.create(description: "side saddle, hand touching seat", number: 25, letter: 'a', points: 3.5)
  StandardSkillEntry.create(description: "side saddle, hand touching seat - c", number: 25, letter: 'b', points: 4.0)
  StandardSkillEntry.create(description: "side saddle freehand", number: 25, letter: 'c', points: 3.7)
  StandardSkillEntry.create(description: "side saddle freehand - c", number: 25, letter: 'd', points: 4.3)
  StandardSkillEntry.create(description: "side saddle freehand - 8", number: 25, letter: 'e', points: 4.8)
  StandardSkillEntry.create(description: "cross over", number: 26, letter: 'a', points: 4.4)
  StandardSkillEntry.create(description: "cross over - c", number: 26, letter: 'b', points: 4.2)
  StandardSkillEntry.create(description: "cross over - 8", number: 26, letter: 'c', points: 5.7)
  StandardSkillEntry.create(description: "cross over bwd", number: 27, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "cross over bwd - c", number: 27, letter: 'b', points: 5.1)
  StandardSkillEntry.create(description: "cross over bwd - 8", number: 27, letter: 'c', points: 7.0)
  StandardSkillEntry.create(description: "side ride", number: 28, letter: 'a', points: 5.9)
  StandardSkillEntry.create(description: "side ride - c", number: 28, letter: 'b', points: 5.6)
  StandardSkillEntry.create(description: "side ride - 8", number: 28, letter: 'c', points: 7.7)
  StandardSkillEntry.create(description: "side ride, one hand", number: 28, letter: 'd', points: 6.2)
  StandardSkillEntry.create(description: "side ride, one hand - c", number: 28, letter: 'e', points: 5.9)
  StandardSkillEntry.create(description: "side ride, one hand - 8", number: 28, letter: 'f', points: 8.1)
  StandardSkillEntry.create(description: "side ride bwd", number: 29, letter: 'a', points: 6.6)
  StandardSkillEntry.create(description: "side ride bwd - c", number: 29, letter: 'b', points: 6.3)
  StandardSkillEntry.create(description: "side ride bwd - 8", number: 29, letter: 'c', points: 8.6)
  StandardSkillEntry.create(description: "side ride bwd, 1 hand", number: 29, letter: 'd', points: 6.8)
  StandardSkillEntry.create(description: "side ride bwd, 1 hand - c", number: 29, letter: 'e', points: 6.5)
  StandardSkillEntry.create(description: "side ride bwd, 1 hand - 8", number: 29, letter: 'f', points: 8.8)
  StandardSkillEntry.create(description: "wheel walk", number: 30, letter: 'a', points: 3.3)
  StandardSkillEntry.create(description: "wheel walk - c", number: 30, letter: 'b', points: 3.8)
  StandardSkillEntry.create(description: "wheel walk - 8", number: 30, letter: 'c', points: 4.3)
  StandardSkillEntry.create(description: "wheel walk bwd", number: 31, letter: 'a', points: 4.4)
  StandardSkillEntry.create(description: "wheel walk bwd - c", number: 31, letter: 'b', points: 5.1)
  StandardSkillEntry.create(description: "wheel walk frame between feet", number: 32, letter: 'a', points: 4.1)
  StandardSkillEntry.create(description: "wheel walk frame between feet - c", number: 32, letter: 'b', points: 4.7)
  StandardSkillEntry.create(description: "wheel walk frame between feet bwd", number: 33, letter: 'a', points: 4.6)
  StandardSkillEntry.create(description: "wheel walk frame between feet bwd - c", number: 33, letter: 'b', points: 5.3)
  StandardSkillEntry.create(description: "wheel walk bwd, feet behind frame", number: 34, letter: 'a', points: 5.0)
  StandardSkillEntry.create(description: "wheel walk bwd, feet behind frame - c", number: 34, letter: 'b', points: 5.8)
  StandardSkillEntry.create(description: "spoke walk bwd, feet behind frame", number: 35, letter: 'a', points: 5.3)
  StandardSkillEntry.create(description: "spoke walk bwd, feet behind frame - c", number: 35, letter: 'b', points: 6.1)
  StandardSkillEntry.create(description: "wheel walk one foot", number: 36, letter: 'a', points: 3.5)
  StandardSkillEntry.create(description: "wheel walk one foot - c", number: 36, letter: 'b', points: 4.3)
  StandardSkillEntry.create(description: "wheel walk one foot - 8", number: 36, letter: 'c', points: 4.8)
  StandardSkillEntry.create(description: "wheel walk one foot ext", number: 36, letter: 'd', points: 4.0)
  StandardSkillEntry.create(description: "wheel walk one foot ext - c", number: 36, letter: 'e', points: 4.6)
  StandardSkillEntry.create(description: "wheel walk one foot ext - 8", number: 36, letter: 'f', points: 5.2)
  StandardSkillEntry.create(description: "ww 1ft crossed", number: 36, letter: 'g', points: 4.6)
  StandardSkillEntry.create(description: "ww 1ft crossed - c", number: 36, letter: 'h', points: 5.3)
  StandardSkillEntry.create(description: "wheel walk bwd one foot", number: 37, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "wheel walk bwd one foot - c", number: 37, letter: 'b', points: 6.2)
  StandardSkillEntry.create(description: "wheel walk bwd one foot ext", number: 37, letter: 'c', points: 6.0)
  StandardSkillEntry.create(description: "wheel walk bwd one foot ext - c", number: 37, letter: 'd', points: 6.9)
  StandardSkillEntry.create(description: "koosh koosh", number: 38, letter: 'a', points: 3.9)
  StandardSkillEntry.create(description: "koosh koosh - c", number: 38, letter: 'b', points: 4.5)
  StandardSkillEntry.create(description: "wheel walk bwd one foot behind frame", number: 38, letter: 'c', points: 5.2)
  StandardSkillEntry.create(description: "wheel walk bwd one foot behind frame - c", number: 38, letter: 'd', points: 6.0)
  StandardSkillEntry.create(description: "hand wheel walk", number: 39, letter: 'a', points: 4.7)
  StandardSkillEntry.create(description: "hand wheel walk - c", number: 39, letter: 'b', points: 5.4)
  StandardSkillEntry.create(description: "hand wheel walk feet out", number: 39, letter: 'c', points: 5.8)
  StandardSkillEntry.create(description: "hand wheel walk feet out - c", number: 39, letter: 'd', points: 6.7)
  StandardSkillEntry.create(description: "one hand wheel walk", number: 40, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "one hand wheel walk - c", number: 40, letter: 'b', points: 6.2)
  StandardSkillEntry.create(description: "one hand wheel walk feet out", number: 40, letter: 'c', points: 6.5)
  StandardSkillEntry.create(description: "one hand wheel walk feet out - c", number: 40, letter: 'd', points: 7.5)
  StandardSkillEntry.create(description: "hand wheel walk, stomach on seat", number: 41, letter: 'a', points: 4.3)
  StandardSkillEntry.create(description: "hand ww, stomach on seat - c", number: 41, letter: 'b', points: 4.9)
  StandardSkillEntry.create(description: "one hand wheel walk, stomach on seat", number: 42, letter: 'a', points: 5.1)
  StandardSkillEntry.create(description: "one hand ww, stomach on seat - c", number: 42, letter: 'b', points: 5.9)
  StandardSkillEntry.create(description: "wheel walk seat in front", number: 43, letter: 'a', points: 6.3)
  StandardSkillEntry.create(description: "wheel walk seat in front - c", number: 43, letter: 'b', points: 7.2)
  StandardSkillEntry.create(description: "wheel walk seat in front, one foot", number: 43, letter: 'c', points: 5.4)
  StandardSkillEntry.create(description: "wheel walk seat in front, one foot extended", number: 43, letter: 'd', points: 6.2)
  StandardSkillEntry.create(description: "wheel walk seat in front bwd, feet behind frame", number: 44, letter: 'a', points: 6.5)
  StandardSkillEntry.create(description: "ww seat in front bwd, feet behind frame - c", number: 44, letter: 'b', points: 7.5)
  StandardSkillEntry.create(description: "ww seat in front bwd, one foot, foot behind frame", number: 44, letter: 'c', points: 6.5)
  StandardSkillEntry.create(description: "ww seat in front bwd, 1ft ext, foot behind frame", number: 44, letter: 'd', points: 6.7)
  StandardSkillEntry.create(description: "wheel walk seat in back", number: 45, letter: 'a', points: 6.4)
  StandardSkillEntry.create(description: "wheel walk seat in back - c", number: 45, letter: 'b', points: 7.4)
  StandardSkillEntry.create(description: "wheel walk seat in back, one foot extended", number: 45, letter: 'c', points: 6.5)
  StandardSkillEntry.create(description: "seat on side, ww, hand touching seat", number: 46, letter: 'a', points: 5.6)
  StandardSkillEntry.create(description: "seat on side, ww", number: 46, letter: 'b', points: 5.8)
  StandardSkillEntry.create(description: "seat on side, ww - c", number: 46, letter: 'c', points: 6.7)
  StandardSkillEntry.create(description: "seat on side, ww 1ft, hand touching seat", number: 46, letter: 'd', points: 5.3)
  StandardSkillEntry.create(description: "seat on side, ww 1ft", number: 46, letter: 'e', points: 5.6)
  StandardSkillEntry.create(description: "seat on side, ww 1ft - c", number: 46, letter: 'f', points: 6.4)
  StandardSkillEntry.create(description: "seat on side, stand up ww 1ft, hand touching seat", number: 46, letter: 'g', points: 5.2)
  StandardSkillEntry.create(description: "seat on side, stand up ww 1ft", number: 46, letter: 'h', points: 5.6)
  StandardSkillEntry.create(description: "seat on side, stand up ww 1ft - c", number: 46, letter: 'i', points: 6.4)
  StandardSkillEntry.create(description: "seat on side, koosh koosh", number: 47, letter: 'a', points: 5.5)
  StandardSkillEntry.create(description: "seat on side, koosh koosh -c", number: 47, letter: 'b', points: 6.3)
  StandardSkillEntry.create(description: "seat on side, stand up koosh koosh", number: 47, letter: 'c', points: 5.6)
  StandardSkillEntry.create(description: "seat on side, stand up koosh koosh -c", number: 47, letter: 'd', points: 6.4)
  StandardSkillEntry.create(description: "sideways wheel walk", number: 48, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "sideways wheel walk - c", number: 48, letter: 'b', points: 6.2)
  StandardSkillEntry.create(description: "sideways wheel walk, one foot", number: 49, letter: 'a', points: 5.6)
  StandardSkillEntry.create(description: "sideways wheel walk, one foot - c", number: 49, letter: 'b', points: 6.4)
  StandardSkillEntry.create(description: "sideways wheel walk, one foot on seat", number: 49, letter: 'c', points: 5.8)
  StandardSkillEntry.create(description: "sideways ww, sitting on seat, 1 hand", number: 50, letter: 'a', points: 6.1)
  StandardSkillEntry.create(description: "sideways ww, sitting on seat, frh", number: 50, letter: 'b', points: 6.3)
  StandardSkillEntry.create(description: "sideways ww, sitting on seat, frh - c", number: 50, letter: 'c', points: 7.2)
  StandardSkillEntry.create(description: "sideways ww, sitting on seat, frh, 1 ft", number: 50, letter: 'd', points: 6.5)
  StandardSkillEntry.create(description: "sideways ww, sitting on seat, frh, 1 ft ext", number: 50, letter: 'e', points: 6.7)
  StandardSkillEntry.create(description: "stand up ww 1 ft", number: 51, letter: 'a', points: 4.2)
  StandardSkillEntry.create(description: "stand up ww 1 ft - c", number: 51, letter: 'b', points: 4.8)
  StandardSkillEntry.create(description: "stand up koosh koosh", number: 52, letter: 'a', points: 4.8)
  StandardSkillEntry.create(description: "stand up koosh koosh - c", number: 52, letter: 'b', points: 5.5)
  StandardSkillEntry.create(description: "stand up ww bwd 1ft", number: 52, letter: 'c', points: 6.0)
  StandardSkillEntry.create(description: "stand up ww bwd 1ft -c", number: 52, letter: 'd', points: 6.9)
  StandardSkillEntry.create(description: "gliding", number: 53, letter: 'a', points: 3.9)
  StandardSkillEntry.create(description: "gliding - c", number: 53, letter: 'b', points: 4.7)
  StandardSkillEntry.create(description: "gliding, foot on frame", number: 53, letter: 'c', points: 3.9)
  StandardSkillEntry.create(description: "gliding, foot on frame - c", number: 53, letter: 'd', points: 4.7)
  StandardSkillEntry.create(description: "gliding, leg ext", number: 53, letter: 'e', points: 4.2)
  StandardSkillEntry.create(description: "gliding, leg ext - c", number: 53, letter: 'f', points: 5.0)
  StandardSkillEntry.create(description: "gliding bwd foot behind frame", number: 54, letter: 'a', points: 5.2)
  StandardSkillEntry.create(description: "gliding bwd foot behind frame - c", number: 54, letter: 'b', points: 6.2)
  StandardSkillEntry.create(description: "gliding bwd foot on frame", number: 54, letter: 'c', points: 5.1)
  StandardSkillEntry.create(description: "gliding bwd foot on frame -c", number: 54, letter: 'd', points: 6.1)
  StandardSkillEntry.create(description: "gliding bwd foot on frame, leg ext", number: 54, letter: 'e', points: 5.7)
  StandardSkillEntry.create(description: "gliding bwd foot on frame, leg ext -c", number: 54, letter: 'f', points: 6.8)
  StandardSkillEntry.create(description: "coasting, leg ext", number: 55, letter: 'a', points: 5.3)
  StandardSkillEntry.create(description: "coasting, leg ext - c", number: 55, letter: 'b', points: 6.1)
  StandardSkillEntry.create(description: "coasting, leg ext - 8", number: 55, letter: 'c', points: 6.9)
  StandardSkillEntry.create(description: "coasting, feet in", number: 55, letter: 'd', points: 5.3)
  StandardSkillEntry.create(description: "coasting, feet in - c", number: 55, letter: 'e', points: 6.1)
  StandardSkillEntry.create(description: "coasting, feet in - 8", number: 55, letter: 'f', points: 6.9)
  StandardSkillEntry.create(description: "coasting bwd, leg ext", number: 56, letter: 'a', points: 6.2)
  StandardSkillEntry.create(description: "coasting bwd, leg ext - c", number: 56, letter: 'b', points: 7.1)
  StandardSkillEntry.create(description: "coasting bwd, leg ext - 8", number: 56, letter: 'c', points: 8.1)
  StandardSkillEntry.create(description: "coasting bwd, feet in", number: 56, letter: 'd', points: 6.0)
  StandardSkillEntry.create(description: "coasting bwd, feet in - c", number: 56, letter: 'e', points: 7.0)
  StandardSkillEntry.create(description: "coasting bwd, feet in - 8", number: 56, letter: 'f', points: 7.8)
  StandardSkillEntry.create(description: "stand up glide", number: 57, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "stand up glide - c", number: 57, letter: 'b', points: 6.5)
  StandardSkillEntry.create(description: "stand up glide, foot on frame", number: 57, letter: 'c', points: 5.4)
  StandardSkillEntry.create(description: "stand up glide, foot on frame - c", number: 57, letter: 'd', points: 6.5)
  StandardSkillEntry.create(description: "stand up glide 1ft ext, 1 hand on seat", number: 57, letter: 'e', points: 6.3)
  StandardSkillEntry.create(description: "stand up glide 1ft ext", number: 57, letter: 'f', points: 6.6)
  StandardSkillEntry.create(description: "stand up glide 1ft ext -c", number: 57, letter: 'g', points: 7.9)
  StandardSkillEntry.create(description: "stand up glide bwd", number: 58, letter: 'a', points: 6.7)
  StandardSkillEntry.create(description: "stand up glide bwd - c", number: 58, letter: 'b', points: 8.0)
  StandardSkillEntry.create(description: "stand up glide bwd, foot on frame", number: 58, letter: 'c', points: 6.7)
  StandardSkillEntry.create(description: "stand up glide bwd, foot on frame - c", number: 58, letter: 'd', points: 8.0)
  StandardSkillEntry.create(description: "stand up glide bwd 1ft ext, 1 hand", number: 58, letter: 'e', points: 7.1)
  StandardSkillEntry.create(description: "stand up glide bwd 1ft ext", number: 58, letter: 'f', points: 7.4)
  StandardSkillEntry.create(description: "stand up glide bwd 1ft ext - c", number: 58, letter: 'g', points: 8.9)
  StandardSkillEntry.create(description: "stand up coast", number: 59, letter: 'a', points: 7.0)
  StandardSkillEntry.create(description: "stand up coast - c", number: 59, letter: 'b', points: 8.4)
  StandardSkillEntry.create(description: "stand up coast - 8", number: 59, letter: 'c', points: 9.5)
  StandardSkillEntry.create(description: "riding to seat in front", number: 101, letter: 'a', points: 1.3)
  StandardSkillEntry.create(description: "riding to stomach on seat", number: 101, letter: 'b', points: 1.5)
  StandardSkillEntry.create(description: "seat in front to riding", number: 102, letter: 'a', points: 1.5)
  StandardSkillEntry.create(description: "stomach on seat to riding", number: 102, letter: 'b', points: 1.6)
  StandardSkillEntry.create(description: "riding to seat in back", number: 103, letter: 'a', points: 1.6)
  StandardSkillEntry.create(description: "seat in back to riding", number: 104, letter: 'a', points: 1.7)
  StandardSkillEntry.create(description: "ww to pedals", number: 105, letter: 'a', points: 2.8)
  StandardSkillEntry.create(description: "ww to riding 1 ft", number: 105, letter: 'b', points: 3.1)
  StandardSkillEntry.create(description: "gliding to pedals", number: 105, letter: 'c', points: 3.3)
  StandardSkillEntry.create(description: "gliding to riding 1 ft", number: 105, letter: 'd', points: 3.5)
  StandardSkillEntry.create(description: "ww 1ft to pedals", number: 105, letter: 'e', points: 3.0)
  StandardSkillEntry.create(description: "pick up seat in front", number: 106, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "pick up seat in front with toe", number: 106, letter: 'b', points: 4.5)
  StandardSkillEntry.create(description: "pick up seat in front free foot", number: 106, letter: 'c', points: 4.2)
  StandardSkillEntry.create(description: "pick up seat in back", number: 107, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "pick up seat in back with heel", number: 107, letter: 'b', points: 4.0)
  StandardSkillEntry.create(description: "pick up seat in back free foot", number: 107, letter: 'c', points: 4.8)
  StandardSkillEntry.create(description: "seat in front to side ride", number: 108, letter: 'a', points: 5.0)
  StandardSkillEntry.create(description: "side ride to seat in front", number: 109, letter: 'a', points: 5.2)
  StandardSkillEntry.create(description: "side ride to hopping on wheel", number: 110, letter: 'a', points: 4.7)
  StandardSkillEntry.create(description: "side ride to sideways wheel walk", number: 110, letter: 'b', points: 5.3)
  StandardSkillEntry.create(description: "idling to stand up ww", number: 111, letter: 'a', points: 3.7)
  StandardSkillEntry.create(description: "idling to stand up ww frh", number: 111, letter: 'b', points: 3.9)
  StandardSkillEntry.create(description: "hopping to stand up ww", number: 111, letter: 'c', points: 3.9)
  StandardSkillEntry.create(description: "hopping to stand up ww frh", number: 111, letter: 'd', points: 4.1)
  StandardSkillEntry.create(description: "stillstand to stand up ww", number: 111, letter: 'e', points: 4.3)
  StandardSkillEntry.create(description: "stillstand to stand up ww frh", number: 111, letter: 'f', points: 4.5)
  StandardSkillEntry.create(description: "riding to stand up ww", number: 111, letter: 'g', points: 4.0)
  StandardSkillEntry.create(description: "riding to stand up ww frh", number: 111, letter: 'h', points: 4.2)
  StandardSkillEntry.create(description: "riding bwd to stand up koosh koosh", number: 111, letter: 'i', points: 4.2)
  StandardSkillEntry.create(description: "riding bwd to stand up koosh koosh frh", number: 111, letter: 'j', points: 4.4)
  StandardSkillEntry.create(description: "1 ft to stand up glide", number: 112, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "1 ft to stand up glide frh", number: 112, letter: 'b', points: 4.1)
  StandardSkillEntry.create(description: "gliding to stand up glide", number: 112, letter: 'c', points: 3.8)
  StandardSkillEntry.create(description: "gliding to stand up glide frh", number: 112, letter: 'd', points: 3.9)
  StandardSkillEntry.create(description: "riding to stand up glide", number: 112, letter: 'e', points: 4.2)
  StandardSkillEntry.create(description: "riding to stand up glide frh", number: 112, letter: 'f', points: 4.3)
  StandardSkillEntry.create(description: "1 ft bwd to stand up glide bwd", number: 113, letter: 'a', points: 5.1)
  StandardSkillEntry.create(description: "1 ft bwd to stand up glide bwd frh", number: 113, letter: 'b', points: 5.3)
  StandardSkillEntry.create(description: "gliding bwd to stand up glide bwd", number: 113, letter: 'c', points: 4.9)
  StandardSkillEntry.create(description: "gliding bwd to stand up glide bwd frh", number: 113, letter: 'd', points: 5.1)
  StandardSkillEntry.create(description: "riding bwd to stand up glide bwd", number: 113, letter: 'e', points: 5.3)
  StandardSkillEntry.create(description: "riding bwd to stand up glide bwd frh", number: 113, letter: 'f', points: 5.5)
  StandardSkillEntry.create(description: "stand up ww to hop on wheel frh", number: 114, letter: 'a', points: 3.6)
  StandardSkillEntry.create(description: "hop on wheel frh to stand up ww", number: 114, letter: 'b', points: 3.6)
  StandardSkillEntry.create(description: "ww to crossover", number: 115, letter: 'a', points: 3.7)
  StandardSkillEntry.create(description: "ww 1ft to crossover", number: 115, letter: 'b', points: 3.8)
  StandardSkillEntry.create(description: "gliding to crossover", number: 115, letter: 'c', points: 4.2)
  StandardSkillEntry.create(description: "crossover to ww", number: 116, letter: 'a', points: 3.7)
  StandardSkillEntry.create(description: "crossover to ww 1ft", number: 116, letter: 'b', points: 3.8)
  StandardSkillEntry.create(description: "riding turn 90", number: 151, letter: 'a', points: 1.3)
  StandardSkillEntry.create(description: "riding turn 180", number: 151, letter: 'b', points: 1.7)
  StandardSkillEntry.create(description: "riding turn 360", number: 151, letter: 'c', points: 2.2)
  StandardSkillEntry.create(description: "bwd riding turn 90", number: 152, letter: 'a', points: 2.3)
  StandardSkillEntry.create(description: "bwd riding turn 180", number: 152, letter: 'b', points: 2.7)
  StandardSkillEntry.create(description: "bwd riding turn 360", number: 152, letter: 'c', points: 3.5)
  StandardSkillEntry.create(description: "stand up full turn, arms in", number: 153, letter: 'a', points: 4.6)
  StandardSkillEntry.create(description: "stand up full turn", number: 153, letter: 'b', points: 4.8)
  StandardSkillEntry.create(description: "stand up 1.5 turns, arms in", number: 153, letter: 'c', points: 4.9)
  StandardSkillEntry.create(description: "stand up 1.5 turns", number: 153, letter: 'd', points: 5.1)
  StandardSkillEntry.create(description: "stand up 2 turns, arms in", number: 153, letter: 'e', points: 5.3)
  StandardSkillEntry.create(description: "stand up 2 turns", number: 153, letter: 'f', points: 5.5)
  StandardSkillEntry.create(description: "stand up 2.5 turns, arms in", number: 153, letter: 'g', points: 5.8)
  StandardSkillEntry.create(description: "stand up 2.5 turns", number: 153, letter: 'h', points: 6.0)
  StandardSkillEntry.create(description: "stand up 3 turns, arms in", number: 153, letter: 'i', points: 6.3)
  StandardSkillEntry.create(description: "stand up 3 turns", number: 153, letter: 'j', points: 6.5)
  StandardSkillEntry.create(description: "back turn", number: 154, letter: 'a', points: 2.6)
  StandardSkillEntry.create(description: "back turn seat in front, touching body", number: 154, letter: 'b', points: 3.0)
  StandardSkillEntry.create(description: "back turn seat in front", number: 154, letter: 'c', points: 3.2)
  StandardSkillEntry.create(description: "back turn seat in back, touching body", number: 154, letter: 'd', points: 3.3)
  StandardSkillEntry.create(description: "back turn seat in back", number: 154, letter: 'e', points: 3.8)
  StandardSkillEntry.create(description: "back turn, 1ft", number: 154, letter: 'f', points: 3.5)
  StandardSkillEntry.create(description: "front turn", number: 155, letter: 'a', points: 3.0)
  StandardSkillEntry.create(description: "front turn seat in front, touching body", number: 155, letter: 'b', points: 3.2)
  StandardSkillEntry.create(description: "front turn seat in front", number: 155, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "front turn seat in back, touching body", number: 155, letter: 'd', points: 3.4)
  StandardSkillEntry.create(description: "front turn seat in back", number: 155, letter: 'e', points: 3.9)
  StandardSkillEntry.create(description: "front turn, 1ft", number: 155, letter: 'f', points: 3.7)
  StandardSkillEntry.create(description: "stand up back turn, arms in", number: 156, letter: 'a', points: 5.2)
  StandardSkillEntry.create(description: "stand up back turn", number: 156, letter: 'b', points: 5.4)
  StandardSkillEntry.create(description: "stand up front turn, arms in", number: 157, letter: 'a', points: 5.3)
  StandardSkillEntry.create(description: "stand up front turn", number: 157, letter: 'b', points: 5.5)
  StandardSkillEntry.create(description: "spin", number: 158, letter: 'a', points: 3.1)
  StandardSkillEntry.create(description: "spin 1ft", number: 158, letter: 'b', points: 3.5)
  StandardSkillEntry.create(description: "spin 1ft ext", number: 158, letter: 'c', points: 3.7)
  StandardSkillEntry.create(description: "backward spin", number: 159, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "backward spin 1ft", number: 159, letter: 'b', points: 4.3)
  StandardSkillEntry.create(description: "backward spin 1ft ext", number: 159, letter: 'c', points: 4.7)
  StandardSkillEntry.create(description: "toe point spin", number: 160, letter: 'a', points: 3.6)
  StandardSkillEntry.create(description: "toe point spin frh", number: 160, letter: 'b', points: 3.7)
  StandardSkillEntry.create(description: "1 ft spin, hand holding foot", number: 160, letter: 'c', points: 3.7)
  StandardSkillEntry.create(description: "toe point bwd spin", number: 161, letter: 'a', points: 4.3)
  StandardSkillEntry.create(description: "toe point bwd spin frh", number: 161, letter: 'b', points: 4.5)
  StandardSkillEntry.create(description: "1 ft spin bwd, hand holding foot", number: 161, letter: 'c', points: 5.0)
  StandardSkillEntry.create(description: "cross over toe point spin", number: 162, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "cross over spin", number: 162, letter: 'b', points: 3.9)
  StandardSkillEntry.create(description: "cross over spin bwd", number: 163, letter: 'a', points: 4.4)
  StandardSkillEntry.create(description: "spin seat in front, seat against body", number: 164, letter: 'a', points: 3.5)
  StandardSkillEntry.create(description: "spin seat in front", number: 164, letter: 'b', points: 3.7)
  StandardSkillEntry.create(description: "spin seat in back, seat against body", number: 165, letter: 'a', points: 3.6)
  StandardSkillEntry.create(description: "spin seat in back", number: 165, letter: 'b', points: 3.9)
  StandardSkillEntry.create(description: "spin seat on side, seat touching body", number: 166, letter: 'a', points: 3.4)
  StandardSkillEntry.create(description: "spin seat on side", number: 166, letter: 'b', points: 3.8)
  StandardSkillEntry.create(description: "pirouette, arms in", number: 167, letter: 'a', points: 3.9)
  StandardSkillEntry.create(description: "pirouette", number: 167, letter: 'b', points: 4.7)
  StandardSkillEntry.create(description: "backward pirouette, arms in", number: 168, letter: 'a', points: 5.2)
  StandardSkillEntry.create(description: "backward pirouette", number: 168, letter: 'b', points: 5.5)
  StandardSkillEntry.create(description: "pirouette seat in front, against bdy, arm in", number: 169, letter: 'a', points: 4.0)
  StandardSkillEntry.create(description: "pirouette seat in front, seat against body", number: 169, letter: 'b', points: 4.7)
  StandardSkillEntry.create(description: "pirouette seat in front, arm in", number: 169, letter: 'c', points: 4.2)
  StandardSkillEntry.create(description: "pirouette seat in front", number: 169, letter: 'd', points: 4.9)
  StandardSkillEntry.create(description: "pirouette seat in back, against bdy, arm in", number: 170, letter: 'a', points: 4.1)
  StandardSkillEntry.create(description: "pirouette seat in back, seat against body", number: 170, letter: 'b', points: 4.8)
  StandardSkillEntry.create(description: "pirouette seat in back, arm in", number: 170, letter: 'c', points: 4.3)
  StandardSkillEntry.create(description: "pirouette seat in back", number: 170, letter: 'd', points: 5.0)
  StandardSkillEntry.create(description: "hop-twist 90", number: 201, letter: 'a', points: 2.3)
  StandardSkillEntry.create(description: "hop-twist 180", number: 201, letter: 'b', points: 2.8)
  StandardSkillEntry.create(description: "hop-twist 360", number: 201, letter: 'c', points: 4.1)
  StandardSkillEntry.create(description: "hop-twist freehand  90", number: 201, letter: 'd', points: 2.5)
  StandardSkillEntry.create(description: "hop-twist freehand 180", number: 201, letter: 'e', points: 3.0)
  StandardSkillEntry.create(description: "hop-twist freehand 360", number: 201, letter: 'f', points: 4.5)
  StandardSkillEntry.create(description: "riding hoptwist 90", number: 202, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "riding hoptwist 180", number: 202, letter: 'b', points: 3.0)
  StandardSkillEntry.create(description: "riding hoptwist 360", number: 202, letter: 'c', points: 4.1)
  StandardSkillEntry.create(description: "riding hoptwist freehand 90", number: 202, letter: 'd', points: 2.6)
  StandardSkillEntry.create(description: "riding hoptwist freehand 180", number: 202, letter: 'e', points: 3.5)
  StandardSkillEntry.create(description: "riding hoptwist freehand 360", number: 202, letter: 'f', points: 4.6)
  StandardSkillEntry.create(description: "hoptwist on wheel 90", number: 203, letter: 'a', points: 3.1)
  StandardSkillEntry.create(description: "hoptwist on wheel 180", number: 203, letter: 'b', points: 3.6)
  StandardSkillEntry.create(description: "hoptwist on wheel freehanded 90", number: 203, letter: 'c', points: 3.7)
  StandardSkillEntry.create(description: "hoptwist on wheel freehanded 180", number: 203, letter: 'd', points: 3.9)
  StandardSkillEntry.create(description: "hop over", number: 204, letter: 'a', points: 2.7)
  StandardSkillEntry.create(description: "sideways hop over", number: 204, letter: 'b', points: 2.6)
  StandardSkillEntry.create(description: "hop over, seat in front", number: 204, letter: 'c', points: 3.1)
  StandardSkillEntry.create(description: "sideways hop over, seat in front, against body", number: 204, letter: 'd', points: 3.0)
  StandardSkillEntry.create(description: "sideways hop over, seat in front", number: 204, letter: 'e', points: 3.3)
  StandardSkillEntry.create(description: "sideways hop over, hopping on wheel", number: 204, letter: 'f', points: 3.3)
  StandardSkillEntry.create(description: "sideways hop over, stand up hopping on wheel frh", number: 204, letter: 'g', points: 3.8)
  StandardSkillEntry.create(description: "wheel grab", number: 205, letter: 'a', points: 1.3)
  StandardSkillEntry.create(description: "wheel grab, 1ft ext", number: 205, letter: 'b', points: 2.2)
  StandardSkillEntry.create(description: "wheel grab, 2ft ext", number: 205, letter: 'c', points: 3.5)
  StandardSkillEntry.create(description: "wheel grab seat in front", number: 205, letter: 'd', points: 3.1)
  StandardSkillEntry.create(description: "wheel grab seat in front, 1ft ext", number: 205, letter: 'e', points: 3.4)
  StandardSkillEntry.create(description: "wheel grab seat in front, 2ft ext", number: 205, letter: 'f', points: 4.0)
  StandardSkillEntry.create(description: "wheel grab seat in front, 2ft ext to back", number: 205, letter: 'g', points: 4.8)
  StandardSkillEntry.create(description: "bounce seat, riding", number: 206, letter: 'a', points: 3.2)
  StandardSkillEntry.create(description: "bounce seat, idling", number: 206, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "bounce seat, hopping", number: 206, letter: 'c', points: 3.0)
  StandardSkillEntry.create(description: "bounce seat in back, riding", number: 206, letter: 'd', points: 3.7)
  StandardSkillEntry.create(description: "bounce seat in back, idling", number: 206, letter: 'e', points: 4.0)
  StandardSkillEntry.create(description: "bounce seat in back, hopping", number: 206, letter: 'f', points: 3.7)
  StandardSkillEntry.create(description: "touch seat on floor", number: 207, letter: 'a', points: 3.1)
  StandardSkillEntry.create(description: "touch seat two times on floor", number: 207, letter: 'b', points: 3.3)
  StandardSkillEntry.create(description: "touch seat three times on floor", number: 207, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "touch the floor", number: 208, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "touch the floor with both hands", number: 208, letter: 'b', points: 3.5)
  StandardSkillEntry.create(description: "touch the floor, seat in front", number: 209, letter: 'a', points: 3.0)
  StandardSkillEntry.create(description: "seat drop", number: 210, letter: 'a', points: 3.3)
  StandardSkillEntry.create(description: "seat drop, twist 90", number: 210, letter: 'b', points: 3.5)
  StandardSkillEntry.create(description: "crank idle kick, seat against body", number: 211, letter: 'a', points: 3.3)
  StandardSkillEntry.create(description: "crank idle kick", number: 211, letter: 'b', points: 3.5)
  StandardSkillEntry.create(description: "crank idle kick, seat against body, high", number: 211, letter: 'c', points: 3.9)
  StandardSkillEntry.create(description: "crank idle kick, high", number: 211, letter: 'd', points: 4.3)
  StandardSkillEntry.create(description: "hop on wheel kick", number: 212, letter: 'a', points: 3.2)
  StandardSkillEntry.create(description: "hop on wheel kick, 2 feet", number: 212, letter: 'b', points: 3.6)
  StandardSkillEntry.create(description: "pedals to hopping on wheel", number: 213, letter: 'a', points: 2.9)
  StandardSkillEntry.create(description: "pedals to hopping on wheel, riding", number: 213, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "wheel walk to hopping on wheel", number: 213, letter: 'c', points: 3.8)
  StandardSkillEntry.create(description: "pedals to stand up hopping on wheel, frh", number: 213, letter: 'd', points: 3.5)
  StandardSkillEntry.create(description: "pedals 270 to hopping on wheel", number: 213, letter: 'e', points: 4.0)
  StandardSkillEntry.create(description: "pedals 450 to hopping on wheel", number: 213, letter: 'f', points: 5.3)
  StandardSkillEntry.create(description: "pedals to sideways wheel walk", number: 213, letter: 'g', points: 3.4)
  StandardSkillEntry.create(description: "pedals 270 to sideways wheel walk", number: 213, letter: 'h', points: 4.7)
  StandardSkillEntry.create(description: "pedals 450 to sideways wheel walk", number: 213, letter: 'i', points: 6.0)
  StandardSkillEntry.create(description: "hopping on wheel to pedals", number: 214, letter: 'a', points: 3.4)
  StandardSkillEntry.create(description: "hopping on wheel to pedals, step down", number: 214, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "hopping on wheel to wheel walk", number: 214, letter: 'c', points: 3.3)
  StandardSkillEntry.create(description: "stand up hopping on wheel freehanded to pedals", number: 214, letter: 'd', points: 4.0)
  StandardSkillEntry.create(description: "hopping on wheel 270 to pedals", number: 214, letter: 'e', points: 4.2)
  StandardSkillEntry.create(description: "hopping on wheel 450 to pedals", number: 214, letter: 'f', points: 5.8)
  StandardSkillEntry.create(description: "sideways wheel walk to pedals", number: 214, letter: 'g', points: 3.9)
  StandardSkillEntry.create(description: "sideways wheel walk 270 to pedals", number: 214, letter: 'h', points: 6.0)
  StandardSkillEntry.create(description: "180 uni spin", number: 215, letter: 'a', points: 3.6)
  StandardSkillEntry.create(description: "360 uni spin", number: 215, letter: 'b', points: 4.6)
  StandardSkillEntry.create(description: "540 uni spin", number: 215, letter: 'c', points: 5.7)
  StandardSkillEntry.create(description: "720 uni spin", number: 215, letter: 'd', points: 6.8)
  StandardSkillEntry.create(description: "180 uni spin to seat in front", number: 215, letter: 'e', points: 3.6)
  StandardSkillEntry.create(description: "360 uni spin to seat in front", number: 215, letter: 'f', points: 4.6)
  StandardSkillEntry.create(description: "540 uni spin to seat in front", number: 215, letter: 'g', points: 5.7)
  StandardSkillEntry.create(description: "180 uni spin to idling one foot", number: 215, letter: 'h', points: 4.0)
  StandardSkillEntry.create(description: "360 uni spin to idling one foot", number: 215, letter: 'i', points: 5.0)
  StandardSkillEntry.create(description: "540 uni spin to idling one foot", number: 215, letter: 'j', points: 6.2)
  StandardSkillEntry.create(description: "180 uni spin to idling 1 ft seat in front", number: 215, letter: 'k', points: 4.7)
  StandardSkillEntry.create(description: "360 uni spin to idling 1 ft seat in front", number: 215, letter: 'l', points: 5.7)
  StandardSkillEntry.create(description: "riding 180? uni spin", number: 215, letter: 'm', points: 3.9)
  StandardSkillEntry.create(description: "riding 360? uni spin", number: 215, letter: 'n', points: 4.9)
  StandardSkillEntry.create(description: "180 uni spin to wheel walk", number: 216, letter: 'a', points: 4.3)
  StandardSkillEntry.create(description: "360 uni spin to wheel walk", number: 216, letter: 'b', points: 5.3)
  StandardSkillEntry.create(description: "180 uni spin to wheel walk one foot", number: 216, letter: 'c', points: 4.5)
  StandardSkillEntry.create(description: "360 uni spin to wheel walk one foot", number: 216, letter: 'd', points: 5.5)
  StandardSkillEntry.create(description: "180 uni spin to stand up hopping on wheel frh", number: 217, letter: 'a', points: 4.5)
  StandardSkillEntry.create(description: "360 uni spin to stand up hopping on wheel frh", number: 217, letter: 'b', points: 5.5)
  StandardSkillEntry.create(description: "180 uni spin on wheel", number: 218, letter: 'a', points: 3.8)
  StandardSkillEntry.create(description: "360 uni spin on wheel", number: 218, letter: 'b', points: 4.8)
  StandardSkillEntry.create(description: "crankflip, feet on pedals", number: 219, letter: 'a', points: 3.8)
  StandardSkillEntry.create(description: "crankflip", number: 219, letter: 'b', points: 5.1)
  StandardSkillEntry.create(description: "double crankflip", number: 219, letter: 'c', points: 5.6)
  StandardSkillEntry.create(description: "triple crankflip", number: 219, letter: 'd', points: 6.1)
  StandardSkillEntry.create(description: "crankflip, seat in front", number: 219, letter: 'e', points: 5.2)
  StandardSkillEntry.create(description: "double crankflip, seat in front", number: 219, letter: 'f', points: 5.7)
  StandardSkillEntry.create(description: "triple crankflip, seat in front", number: 219, letter: 'g', points: 6.2)
  StandardSkillEntry.create(description: "crankflip 180 unispin", number: 220, letter: 'a', points: 5.5)
  StandardSkillEntry.create(description: "crankflip 360 unispin", number: 220, letter: 'b', points: 6.5)
  StandardSkillEntry.create(description: "crankflip 540 unispin", number: 220, letter: 'c', points: 7.5)
  StandardSkillEntry.create(description: "double crankflip 180 unispin", number: 220, letter: 'd', points: 5.9)
  StandardSkillEntry.create(description: "double crankflip 360 unispin", number: 220, letter: 'e', points: 6.9)
  StandardSkillEntry.create(description: "double crankflip 540 unispin", number: 220, letter: 'f', points: 7.9)
  StandardSkillEntry.create(description: "crank flip, standing on frame", number: 221, letter: 'a', points: 4.4)
  StandardSkillEntry.create(description: "leg around, riding to riding", number: 222, letter: 'a', points: 3.3)
  StandardSkillEntry.create(description: "leg around twice, riding to riding", number: 222, letter: 'b', points: 4.4)
  StandardSkillEntry.create(description: "leg around, riding to seat on side, 1 hand", number: 222, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "leg around, riding to seat on side", number: 222, letter: 'd', points: 3.0)
  StandardSkillEntry.create(description: "leg around, riding to crank idle, 1 hand", number: 222, letter: 'e', points: 3.6)
  StandardSkillEntry.create(description: "leg around, riding to crank idle", number: 222, letter: 'f', points: 3.2)
  StandardSkillEntry.create(description: "leg around, riding to crank idle, rev", number: 222, letter: 'g', points: 3.3)
  StandardSkillEntry.create(description: "leg around, riding to seat in back", number: 222, letter: 'h', points: 3.6)
  StandardSkillEntry.create(description: "leg around, seat on side to riding", number: 223, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "leg around, seat on side to crank idle", number: 223, letter: 'b', points: 2.6)
  StandardSkillEntry.create(description: "leg around, seat on side to seat in front", number: 223, letter: 'c', points: 3.2)
  StandardSkillEntry.create(description: "leg around, seat on side to seat in front, rev", number: 223, letter: 'd', points: 3.2)
  StandardSkillEntry.create(description: "leg around, seat on side to side hopping", number: 223, letter: 'e', points: 3.4)
  StandardSkillEntry.create(description: "leg around, crank idle to riding, 1 hand", number: 224, letter: 'a', points: 2.6)
  StandardSkillEntry.create(description: "leg around, crank idle to riding, frh", number: 224, letter: 'b', points: 3.1)
  StandardSkillEntry.create(description: "leg around, crank idle to 1ft idle", number: 224, letter: 'c', points: 3.1)
  StandardSkillEntry.create(description: "leg around, crank idle to seat on side", number: 224, letter: 'd', points: 2.6)
  StandardSkillEntry.create(description: "leg around, crank idle to seat in front", number: 224, letter: 'e', points: 3.4)
  StandardSkillEntry.create(description: "leg around, crank idle to crank idle", number: 224, letter: 'f', points: 3.8)
  StandardSkillEntry.create(description: "crank idle to side hopping", number: 224, letter: 'g', points: 3.8)
  StandardSkillEntry.create(description: "crank idle to hop on wheel", number: 224, letter: 'h', points: 3.9)
  StandardSkillEntry.create(description: "crank idle to hop on wheel, jump", number: 224, letter: 'i', points: 4.1)
  StandardSkillEntry.create(description: "leg around, seat in front to riding", number: 225, letter: 'a', points: 2.7)
  StandardSkillEntry.create(description: "leg around twice, seat in front to riding", number: 225, letter: 'b', points: 3.9)
  StandardSkillEntry.create(description: "leg around, seat in front to seat in front", number: 225, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "leg around, seat in front to seat on side", number: 225, letter: 'd', points: 3.0)
  StandardSkillEntry.create(description: "leg around, seat in front to crank idle", number: 225, letter: 'e', points: 3.2)
  StandardSkillEntry.create(description: "leg around, seat in front to seat in back", number: 225, letter: 'f', points: 3.4)
  StandardSkillEntry.create(description: "leg around, seat in back to riding", number: 226, letter: 'a', points: 3.7)
  StandardSkillEntry.create(description: "leg around twice, seat in back to riding", number: 226, letter: 'b', points: 4.4)
  StandardSkillEntry.create(description: "step around", number: 227, letter: 'a', points: 3.9)
  StandardSkillEntry.create(description: "jump around", number: 227, letter: 'b', points: 4.9)
  StandardSkillEntry.create(description: "inverse", number: 227, letter: 'c', points: 4.8)
  StandardSkillEntry.create(description: "180 unispin, 180 hoptwist", number: 228, letter: 'a', points: 5.1)
  StandardSkillEntry.create(description: "360 unispin, 180 hoptwist", number: 228, letter: 'b', points: 5.4)
  StandardSkillEntry.create(description: "540 unispin, 180 hoptwist", number: 228, letter: 'c', points: 5.8)
  StandardSkillEntry.create(description: "360 unispin, 180 hoptwist, opposite", number: 228, letter: 'd', points: 5.8)
  StandardSkillEntry.create(description: "540 unispin, 180 hoptwist, opposite", number: 228, letter: 'e', points: 6.3)
  StandardSkillEntry.create(description: "180 sidespin", number: 229, letter: 'a', points: 5.4)
  StandardSkillEntry.create(description: "360 sidespin", number: 229, letter: 'b', points: 5.8)
  StandardSkillEntry.create(description: "540 sidespin", number: 229, letter: 'c', points: 6.3)
  StandardSkillEntry.create(description: "idling", number: 251, letter: 'a', points: 1.8)
  StandardSkillEntry.create(description: "idling one foot", number: 251, letter: 'b', points: 2.1)
  StandardSkillEntry.create(description: "idling one foot ext", number: 251, letter: 'c', points: 2.3)
  StandardSkillEntry.create(description: "idling one foot crossed", number: 251, letter: 'd', points: 2.3)
  StandardSkillEntry.create(description: "idling seat in front, seat against body", number: 252, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "idling seat in front", number: 252, letter: 'b', points: 2.8)
  StandardSkillEntry.create(description: "idling 1ft seat in front, seat against body", number: 252, letter: 'c', points: 2.9)
  StandardSkillEntry.create(description: "idling 1ft seat in front", number: 252, letter: 'd', points: 3.3)
  StandardSkillEntry.create(description: "idling 1ft seat in front ext, seat against body", number: 252, letter: 'e', points: 3.2)
  StandardSkillEntry.create(description: "idling seat in back, seat against body", number: 252, letter: 'f', points: 3.1)
  StandardSkillEntry.create(description: "idling seat in back", number: 252, letter: 'g', points: 3.4)
  StandardSkillEntry.create(description: "idling seat on side, seat touching body", number: 253, letter: 'a', points: 2.7)
  StandardSkillEntry.create(description: "idling seat on side freehand, touching body", number: 253, letter: 'b', points: 2.9)
  StandardSkillEntry.create(description: "idling seat on side", number: 253, letter: 'c', points: 3.0)
  StandardSkillEntry.create(description: "idling 1ft seat on side, touching body", number: 253, letter: 'd', points: 3.1)
  StandardSkillEntry.create(description: "idling 1ft seat on side", number: 253, letter: 'e', points: 3.5)
  StandardSkillEntry.create(description: "idling 1ft ext seat on side, touching body", number: 253, letter: 'f', points: 3.6)
  StandardSkillEntry.create(description: "idling 1ft ext seat on side", number: 253, letter: 'g', points: 4.2)
  StandardSkillEntry.create(description: "side idle", number: 253, letter: 'h', points: 4.0)
  StandardSkillEntry.create(description: "side idle, 1 hand", number: 253, letter: 'i', points: 4.1)
  StandardSkillEntry.create(description: "crank idle, seat against body", number: 254, letter: 'a', points: 2.9)
  StandardSkillEntry.create(description: "crank idle freehand, seat against body", number: 254, letter: 'b', points: 3.1)
  StandardSkillEntry.create(description: "crank idle", number: 254, letter: 'c', points: 3.2)
  StandardSkillEntry.create(description: "wheel idle", number: 255, letter: 'a', points: 3.7)
  StandardSkillEntry.create(description: "wheel idle, 1ft", number: 255, letter: 'b', points: 3.6)
  StandardSkillEntry.create(description: "wheel idle, 1ft ext", number: 255, letter: 'c', points: 3.8)
  StandardSkillEntry.create(description: "twisting", number: 256, letter: 'a', points: 2.6)
  StandardSkillEntry.create(description: "stillstand", number: 257, letter: 'a', points: 3.6)
  StandardSkillEntry.create(description: "hopping", number: 258, letter: 'a', points: 1.8)
  StandardSkillEntry.create(description: "hopping freehand", number: 258, letter: 'b', points: 2.0)
  StandardSkillEntry.create(description: "hopping seat in front, seat against body", number: 259, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "hopping seat in front", number: 259, letter: 'b', points: 2.8)
  StandardSkillEntry.create(description: "hopping seat in back, seat against body", number: 259, letter: 'c', points: 3.1)
  StandardSkillEntry.create(description: "hopping seat in back", number: 259, letter: 'd', points: 3.4)
  StandardSkillEntry.create(description: "hopping on wheel", number: 260, letter: 'a', points: 2.6)
  StandardSkillEntry.create(description: "hopping on wheel, sitting", number: 260, letter: 'b', points: 3.2)
  StandardSkillEntry.create(description: "hopping on wheel, sitting, freehand", number: 260, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "stand up hopping on wheel, 1 hand", number: 260, letter: 'd', points: 3.1)
  StandardSkillEntry.create(description: "stand up hopping on wheel, freehanded", number: 260, letter: 'e', points: 3.6)
  StandardSkillEntry.create(description: "hoptwisting", number: 261, letter: 'a', points: 2.6)
  StandardSkillEntry.create(description: "side hopping", number: 262, letter: 'a', points: 2.9)
  StandardSkillEntry.create(description: "side hopping, foot touching tire", number: 262, letter: 'b', points: 2.8)
  StandardSkillEntry.create(description: "mount, 1 hand", number: 301, letter: 'a', points: 1.2)
  StandardSkillEntry.create(description: "mount", number: 301, letter: 'b', points: 1.3)
  StandardSkillEntry.create(description: "mount to idle", number: 301, letter: 'c', points: 1.5)
  StandardSkillEntry.create(description: "mount to 1 ft idle", number: 301, letter: 'd', points: 2.0)
  StandardSkillEntry.create(description: "mount to 1 ft ext idle", number: 301, letter: 'e', points: 2.5)
  StandardSkillEntry.create(description: "rolling mount", number: 302, letter: 'a', points: 1.8)
  StandardSkillEntry.create(description: "rolling mount to 1 ft", number: 302, letter: 'b', points: 2.5)
  StandardSkillEntry.create(description: "rolling mount to 1 ft ext", number: 302, letter: 'c', points: 2.7)
  StandardSkillEntry.create(description: "rolling mount to gliding", number: 302, letter: 'd', points: 3.7)
  StandardSkillEntry.create(description: "rolling mount to coasting", number: 302, letter: 'e', points: 4.5)
  StandardSkillEntry.create(description: "back mount", number: 303, letter: 'a', points: 1.9)
  StandardSkillEntry.create(description: "back mount to idle", number: 303, letter: 'b', points: 2.1)
  StandardSkillEntry.create(description: "back mount to 1 ft idle", number: 303, letter: 'c', points: 2.6)
  StandardSkillEntry.create(description: "back mount to 1 ft ext idle", number: 303, letter: 'd', points: 3.1)
  StandardSkillEntry.create(description: "back mount to ww", number: 303, letter: 'e', points: 2.7)
  StandardSkillEntry.create(description: "back mount to ww 1 ft", number: 303, letter: 'f', points: 3.2)
  StandardSkillEntry.create(description: "back mount to ww 1 ft ext", number: 303, letter: 'g', points: 3.5)
  StandardSkillEntry.create(description: "back mount to stand up ww", number: 303, letter: 'h', points: 4.0)
  StandardSkillEntry.create(description: "mount to stomach on seat, 1 hand on seat", number: 304, letter: 'a', points: 1.5)
  StandardSkillEntry.create(description: "mount to stomach on seat", number: 304, letter: 'b', points: 2.0)
  StandardSkillEntry.create(description: "mount to seat in front, touching body", number: 304, letter: 'c', points: 2.0)
  StandardSkillEntry.create(description: "mount to seat in front", number: 304, letter: 'd', points: 2.4)
  StandardSkillEntry.create(description: "side mount", number: 305, letter: 'a', points: 1.8)
  StandardSkillEntry.create(description: "side mount leg around", number: 305, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "side mount leg around twice", number: 305, letter: 'c', points: 4.9)
  StandardSkillEntry.create(description: "side mount from on wheel", number: 305, letter: 'd', points: 2.5)
  StandardSkillEntry.create(description: "side mount from on wheel leg around", number: 305, letter: 'e', points: 4.1)
  StandardSkillEntry.create(description: "side mount reverse", number: 306, letter: 'a', points: 1.8)
  StandardSkillEntry.create(description: "side mount reverse leg around", number: 306, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "side mount reverse leg around twice", number: 306, letter: 'c', points: 4.9)
  StandardSkillEntry.create(description: "side mount reverse from on wheel", number: 306, letter: 'd', points: 2.5)
  StandardSkillEntry.create(description: "side mount reverse from on wheel leg around", number: 306, letter: 'e', points: 4.1)
  StandardSkillEntry.create(description: "jump mount", number: 307, letter: 'a', points: 2.2)
  StandardSkillEntry.create(description: "free jump mount", number: 307, letter: 'b', points: 2.7)
  StandardSkillEntry.create(description: "jump mount to seat in front", number: 307, letter: 'c', points: 2.5)
  StandardSkillEntry.create(description: "jump mount to seat in back", number: 307, letter: 'd', points: 2.7)
  StandardSkillEntry.create(description: "jump mount to wheel walk", number: 307, letter: 'e', points: 2.9)
  StandardSkillEntry.create(description: "jump mount from on wheel", number: 307, letter: 'f', points: 2.9)
  StandardSkillEntry.create(description: "180 uni spin jump mount", number: 307, letter: 'g', points: 2.8)
  StandardSkillEntry.create(description: "360 uni spin jump mount", number: 307, letter: 'h', points: 3.0)
  StandardSkillEntry.create(description: "turn around jump mount", number: 307, letter: 'i', points: 3.0)
  StandardSkillEntry.create(description: "jump mount to stand up ww", number: 307, letter: 'j', points: 3.8)
  StandardSkillEntry.create(description: "free jump mount to seat drag in front", number: 307, letter: 'k', points: 4.2)
  StandardSkillEntry.create(description: "jump mount to seat drag in front", number: 307, letter: 'l', points: 4.6)
  StandardSkillEntry.create(description: "jump mount to seat drag in back, holding wheel", number: 307, letter: 'm', points: 4.1)
  StandardSkillEntry.create(description: "jump mount to seat drag in back, feet holding seat", number: 307, letter: 'n', points: 4.8)
  StandardSkillEntry.create(description: "side jump mount", number: 308, letter: 'a', points: 2.5)
  StandardSkillEntry.create(description: "free side jump mount", number: 308, letter: 'b', points: 3.0)
  StandardSkillEntry.create(description: "side jump mount to seat on side", number: 308, letter: 'c', points: 3.1)
  StandardSkillEntry.create(description: "side jump mount to ww", number: 308, letter: 'd', points: 3.8)
  StandardSkillEntry.create(description: "side jump mount to ww 1 ft", number: 308, letter: 'e', points: 3.9)
  StandardSkillEntry.create(description: "side jump mount to ww 1 ft ext", number: 308, letter: 'f', points: 4.1)
  StandardSkillEntry.create(description: "180 uni spin side jump mount", number: 308, letter: 'g', points: 3.8)
  StandardSkillEntry.create(description: "360 uni spin side jump mount", number: 308, letter: 'h', points: 5.2)
  StandardSkillEntry.create(description: "rolling side jump mount to gliding", number: 308, letter: 'i', points: 4.3)
  StandardSkillEntry.create(description: "spin mount 360", number: 309, letter: 'a', points: 2.4)
  StandardSkillEntry.create(description: "spin mount 720", number: 309, letter: 'b', points: 3.4)
  StandardSkillEntry.create(description: "kick up mount, 1 hand on seat", number: 310, letter: 'a', points: 2.8)
  StandardSkillEntry.create(description: "kick up", number: 310, letter: 'b', points: 3.2)
  StandardSkillEntry.create(description: "kick up to wheel walk", number: 310, letter: 'c', points: 3.4)
  StandardSkillEntry.create(description: "kick up mount to ww 1 ft", number: 310, letter: 'd', points: 3.6)
  StandardSkillEntry.create(description: "kick up mount to ww 1 ft ext", number: 310, letter: 'e', points: 3.8)
  StandardSkillEntry.create(description: "pick up", number: 311, letter: 'a', points: 3.2)
  StandardSkillEntry.create(description: "swing up mount", number: 312, letter: 'a', points: 3.2)
  StandardSkillEntry.create(description: "swing up mount, frh", number: 312, letter: 'b', points: 4.0)
  StandardSkillEntry.create(description: "push up mount", number: 313, letter: 'a', points: 3.8)
end
