class AddForeignKeyIndexes < ActiveRecord::Migration
  def change
    add_index "additional_registrant_accesses", ["user_id"], name: "index_additional_registrant_accesses_user_id"
    add_index "additional_registrant_accesses", ["registrant_id"], name: "index_additional_registrant_accesses_registrant_id"
    add_index "age_group_entries", ["age_group_type_id"], name: "index_age_group_entries_age_group_type_id"
    add_index "age_group_entries", ["wheel_size_id"], name: "index_age_group_entries_wheel_size_id"
    add_index "boundary_scores", ["competitor_id"], name: "index_boundary_scores_competitor_id"
    add_index "boundary_scores", ["judge_id"], name: "index_boundary_scores_judge_id"
    add_index "competitors", ["event_category_id"], name: "index_competitors_event_category_id"
    add_index "distance_attempts", ["competitor_id"], name: "index_distance_attempts_competitor_id"
    add_index "distance_attempts", ["judge_id"], name: "index_distance_attempts_judge_id"
    add_index "event_categories", ["age_group_type_id"], name: "index_event_categories_age_group_type_id"
    add_index "events", ["category_id"], name: "index_events_category_id"
    add_index "expense_items", ["expense_group_id"], name: "index_expense_items_expense_group_id"
    add_index "judges", ["event_category_id"], name: "index_judges_event_category_id"
    add_index "judges", ["judge_type_id"], name: "index_judges_judge_type_id"
    add_index "judges", ["user_id"], name: "index_judges_user_id"
    add_index "members", ["competitor_id"], name: "index_members_competitor_id"
    add_index "members", ["registrant_id"], name: "index_members_registrant_id"
    add_index "payment_details", ["payment_id"], name: "index_payment_details_payment_id"
    add_index "payment_details", ["registrant_id"], name: "index_payment_details_registrant_id"
    add_index "payment_details", ["expense_item_id"], name: "index_payment_details_expense_item_id"
    add_index "payments", ["user_id"], name: "index_payments_user_id"
    add_index "registrant_choices", ["event_choice_id"], name: "index_registrant_choices_event_choice_id"
    add_index "registrant_event_sign_ups", ["event_category_id"], name: "index_registrant_event_sign_ups_event_category_id"
    add_index "registrant_event_sign_ups", ["event_id"], name: "index_registrant_event_sign_ups_event_id"
    add_index "registrant_expense_items", ["registrant_id"], name: "index_registrant_expense_items_registrant_id"
    add_index "registrant_expense_items", ["expense_item_id"], name: "index_registrant_expense_items_expense_item_id"
    add_index "scores", ["competitor_id"], name: "index_scores_competitor_id"
    add_index "scores", ["judge_id"], name: "index_scores_judge_id"
    add_index "street_scores", ["competitor_id"], name: "index_street_scores_competitor_id"
    add_index "street_scores", ["judge_id"], name: "index_street_scores_judge_id"
  end
end
