require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EventChoicesController do
  before(:each) do
    sign_in FactoryGirl.create(:admin_user)
  end

  # This should return the minimal set of attributes required to create a valid
  # EventChoice. As you add validations to EventChoice, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
    export_name: "100m",
    cell_type: "boolean",
    event_id: 1
    }
  end

  describe "GET index" do
    it "assigns all event_choices as @event_choices" do
      event_choice = EventChoice.create! valid_attributes
      get :index, {}
      assigns(:event_choices).should eq([event_choice])
    end
  end

  describe "GET show" do
    it "assigns the requested event_choice as @event_choice" do
      event_choice = EventChoice.create! valid_attributes
      get :show, {:id => event_choice.to_param}
      assigns(:event_choice).should eq(event_choice)
    end
  end

  describe "GET new" do
    it "assigns a new event_choice as @event_choice" do
      get :new, {}
      assigns(:event_choice).should be_a_new(EventChoice)
    end
  end

  describe "GET edit" do
    it "assigns the requested event_choice as @event_choice" do
      event_choice = EventChoice.create! valid_attributes
      get :edit, {:id => event_choice.to_param}
      assigns(:event_choice).should eq(event_choice)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new EventChoice" do
        expect {
          post :create, {:event_choice => valid_attributes}
        }.to change(EventChoice, :count).by(1)
      end

      it "assigns a newly created event_choice as @event_choice" do
        post :create, {:event_choice => valid_attributes}
        assigns(:event_choice).should be_a(EventChoice)
        assigns(:event_choice).should be_persisted
      end

      it "redirects to the created event_choice" do
        post :create, {:event_choice => valid_attributes}
        response.should redirect_to(EventChoice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved event_choice as @event_choice" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventChoice.any_instance.stub(:save).and_return(false)
        post :create, {:event_choice => {}}
        assigns(:event_choice).should be_a_new(EventChoice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        EventChoice.any_instance.stub(:save).and_return(false)
        post :create, {:event_choice => {}}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested event_choice" do
        event_choice = EventChoice.create! valid_attributes
        # Assuming there are no other event_choices in the database, this
        # specifies that the EventChoice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        EventChoice.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => event_choice.to_param, :event_choice => {'these' => 'params'}}
      end

      it "assigns the requested event_choice as @event_choice" do
        event_choice = EventChoice.create! valid_attributes
        put :update, {:id => event_choice.to_param, :event_choice => valid_attributes}
        assigns(:event_choice).should eq(event_choice)
      end

      it "redirects to the event_choice" do
        event_choice = EventChoice.create! valid_attributes
        put :update, {:id => event_choice.to_param, :event_choice => valid_attributes}
        response.should redirect_to(event_choice)
      end
    end

    describe "with invalid params" do
      it "assigns the event_choice as @event_choice" do
        event_choice = EventChoice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventChoice.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_choice.to_param, :event_choice => {}}
        assigns(:event_choice).should eq(event_choice)
      end

      it "re-renders the 'edit' template" do
        event_choice = EventChoice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        EventChoice.any_instance.stub(:save).and_return(false)
        put :update, {:id => event_choice.to_param, :event_choice => {}}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested event_choice" do
      event_choice = EventChoice.create! valid_attributes
      expect {
        delete :destroy, {:id => event_choice.to_param}
      }.to change(EventChoice, :count).by(-1)
    end

    it "redirects to the event_choices list" do
      event_choice = EventChoice.create! valid_attributes
      delete :destroy, {:id => event_choice.to_param}
      response.should redirect_to(event_choices_url)
    end
  end

end
